name: Lighthouse

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-lighthouse:
    name: Run lighthouse
    runs-on: ubuntu-latest

    steps:
      - name: Lighthouse CI Action
      uses: treosh/lighthouse-ci-action@v10
